/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FerzanRouteImport } from './routes/ferzan'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiLaunchesRouteImport } from './routes/api/launches'
import { Route as ApiRelayStatusRouteImport } from './routes/api/relay-status'
import { Route as PAddressRouteImport } from './routes/p/$address'
import { Route as TIdRouteImport } from './routes/t/$id'
import { Route as CChainAddressRouteImport } from './routes/c/$chain/$address'
import { Route as CoinChainCurveRouteImport } from './routes/coin/$chain/$curve'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FerzanRoute = FerzanRouteImport.update({
  id: '/ferzan',
  path: '/ferzan',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLaunchesRoute = ApiLaunchesRouteImport.update({
  id: '/api/launches',
  path: '/api/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelayStatusRoute = ApiRelayStatusRouteImport.update({
  id: '/api/relay-status',
  path: '/api/relay-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PAddressRoute = PAddressRouteImport.update({
  id: '/p/$address',
  path: '/p/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CChainAddressRoute = CChainAddressRouteImport.update({
  id: '/c/$chain/$address',
  path: '/c/$chain/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinChainCurveRoute = CoinChainCurveRouteImport.update({
  id: '/coin/$chain/$curve',
  path: '/coin/$chain/$curve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/docs': typeof DocsRoute
  '/ferzan': typeof FerzanRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/launches': typeof ApiLaunchesRoute
  '/api/relay-status': typeof ApiRelayStatusRoute
  '/p/$address': typeof PAddressRoute
  '/t/$id': typeof TIdRoute
  '/c/$chain/$address': typeof CChainAddressRoute
  '/coin/$chain/$curve': typeof CoinChainCurveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/docs': typeof DocsRoute
  '/ferzan': typeof FerzanRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/launches': typeof ApiLaunchesRoute
  '/api/relay-status': typeof ApiRelayStatusRoute
  '/p/$address': typeof PAddressRoute
  '/t/$id': typeof TIdRoute
  '/c/$chain/$address': typeof CChainAddressRoute
  '/coin/$chain/$curve': typeof CoinChainCurveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRoute
  '/docs': typeof DocsRoute
  '/ferzan': typeof FerzanRoute
  '/launch': typeof LaunchRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/launches': typeof ApiLaunchesRoute
  '/api/relay-status': typeof ApiRelayStatusRoute
  '/p/$address': typeof PAddressRoute
  '/t/$id': typeof TIdRoute
  '/c/$chain/$address': typeof CChainAddressRoute
  '/coin/$chain/$curve': typeof CoinChainCurveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/docs'
    | '/ferzan'
    | '/launch'
    | '/leaderboard'
    | '/login'
    | '/terms'
    | '/api/launches'
    | '/api/relay-status'
    | '/p/$address'
    | '/t/$id'
    | '/c/$chain/$address'
    | '/coin/$chain/$curve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/docs'
    | '/ferzan'
    | '/launch'
    | '/leaderboard'
    | '/login'
    | '/terms'
    | '/api/launches'
    | '/api/relay-status'
    | '/p/$address'
    | '/t/$id'
    | '/c/$chain/$address'
    | '/coin/$chain/$curve'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/docs'
    | '/ferzan'
    | '/launch'
    | '/leaderboard'
    | '/login'
    | '/terms'
    | '/api/launches'
    | '/api/relay-status'
    | '/p/$address'
    | '/t/$id'
    | '/c/$chain/$address'
    | '/coin/$chain/$curve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRoute
  DocsRoute: typeof DocsRoute
  FerzanRoute: typeof FerzanRoute
  LaunchRoute: typeof LaunchRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  TermsRoute: typeof TermsRoute
  ApiLaunchesRoute: typeof ApiLaunchesRoute
  ApiRelayStatusRoute: typeof ApiRelayStatusRoute
  PAddressRoute: typeof PAddressRoute
  TIdRoute: typeof TIdRoute
  CChainAddressRoute: typeof CChainAddressRoute
  CoinChainCurveRoute: typeof CoinChainCurveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferzan': {
      id: '/ferzan'
      path: '/ferzan'
      fullPath: '/ferzan'
      preLoaderRoute: typeof FerzanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/launches': {
      id: '/api/launches'
      path: '/api/launches'
      fullPath: '/api/launches'
      preLoaderRoute: typeof ApiLaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relay-status': {
      id: '/api/relay-status'
      path: '/api/relay-status'
      fullPath: '/api/relay-status'
      preLoaderRoute: typeof ApiRelayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$address': {
      id: '/p/$address'
      path: '/p/$address'
      fullPath: '/p/$address'
      preLoaderRoute: typeof PAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chain/$address': {
      id: '/c/$chain/$address'
      path: '/c/$chain/$address'
      fullPath: '/c/$chain/$address'
      preLoaderRoute: typeof CChainAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$chain/$curve': {
      id: '/coin/$chain/$curve'
      path: '/coin/$chain/$curve'
      fullPath: '/coin/$chain/$curve'
      preLoaderRoute: typeof CoinChainCurveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRoute,
  DocsRoute: DocsRoute,
  FerzanRoute: FerzanRoute,
  LaunchRoute: LaunchRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  TermsRoute: TermsRoute,
  ApiLaunchesRoute: ApiLaunchesRoute,
  ApiRelayStatusRoute: ApiRelayStatusRoute,
  PAddressRoute: PAddressRoute,
  TIdRoute: TIdRoute,
  CChainAddressRoute: CChainAddressRoute,
  CoinChainCurveRoute: CoinChainCurveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
